apiVersion: v1
kind: Service
metadata:
  name: feed-lb
spec:
  type: LoadBalancer
  ports:
  - name: feed
    port: 8081
    protocol: TCP
    targetPort: 8080
  selector:
    app: vespa-feed-container

