apiVersion: v1
kind: Service
metadata:
  name: query-lb
spec:
  type: LoadBalancer
  ports:
  - name: query
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: vespa-query-container

