# Copyright Vespa.ai. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
apiVersion: v1
kind: ConfigMap
metadata:
  name: vespa-config
data:
  VESPA_CONFIGSERVERS: "vespa-configserver-0.vespa-internal.default.svc.cluster.local,
  vespa-configserver-1.vespa-internal.default.svc.cluster.local,
  vespa-configserver-2.vespa-internal.default.svc.cluster.local"
  VESPA_CONFIGSERVER_JVMARGS: "-Xms32M -Xmx128M"
  VESPA_CONFIGPROXY_JVMARGS: "-Xms32M -Xmx32M"

# The JVMARGS settings are to minimize, for demo purposes only -
# remove for production use.
